### ISSUE TITLE
Bug with JArray compares

### ISSUE THREAD

**Issue by Isopolito** [icalvo/icm.jsondiff#1]
Hi, 

Great project, just what I needed. It appears that there is a bug in JsonDiff.cs, line 90, in the DiffArray method.  Diff is called with the same json data for both arguments. Here it is with context: 

```
    foreach (Difference difference in Diff(json1.Children().ElementAt(i), **json1**.Children().ElementAt(i), path1 + "[" + i + "]"))
```

**Comment by icalvo** [comment]
Hi @Isopolito, thank you! You're right, there was an error there. This was more a gist than a real project, but given that there's at least one user ;) I've revamped it, basically rewritten the whole thing and added a test suite. It still works in a similar way but it's organized better.

**Comment by Isopolito** [comment]
Awesome thanks! I stumbled across this because I'm building regression testing around an api that returns a JSON payload. The API returns json data and the order of the data in the arrays is usually different every call. I haven't been able to find any lib that can handle this situation--they all flag this out as a difference in the data which causes false positives in our tests. So, I was going to work on adding it into this...

**Comment by icalvo** [comment]
You're welcome, feel free to send any other PR.
